App.Show = Em.Object.extend()

App.Show.reopenClass
   # App.Show.findAll()
   findAll: ->
      url = 'http://serialgraphy.com/api/?callback=?'
      
      $.getJSON(url).then (data) ->
         today = new Date
         shows = Em.A()
         data.forEach (date) ->
            date.episodes.forEach (show) ->
               # We don't want aired shows
               unless new Date(show.episode.first_aired_iso) < today
                  shows.pushObject(App.Show.create(show))
         shows

# App.Show = DS.Model.extend
#   date    : DS.attr('date')
#   episodes: DS.attr()

# App.Show.FIXTURES = [
#    {
#       "id" : "1",
#       "date":"2013-11-09",
#       "episodes":[
#          {
#             "show":{
#                "title":"SAF3",
#                "year":2013,
#                "url":"http:\/\/trakt.tv\/show\/saf3",
#                "first_aired":1379746800,
#                "first_aired_iso":"2013-09-21T00:00:00-04:00",
#                "first_aired_localized":1379746800,
#                "first_aired_utc":1379736000,
#                "country":"United States",
#                "overview":"The series follows Southern California's elite rescue task force, SAF3 (pronouced \"safe\") , consists of the cream-of-the-crop from the sea, air, and fire divisions of the Malibu Fire Department. They are the heroes who answer the most challenging calls; specialists who collaborate, coordinate, and initiate daring rescues in the most dangerous venues to save human life, always aware of the harsh reality that one of them may not return.",
#                "runtime":60,
#                "network":"Syndication",
#                "air_day":"Saturday",
#                "air_day_localized":"Saturday",
#                "air_day_utc":"Friday",
#                "air_time":"12:00am",
#                "air_time_localized":"12:00am",
#                "air_time_utc":"9:00pm",
#                "certification":"",
#                "imdb_id":"tt2497788",
#                "tvdb_id":"273493",
#                "tvrage_id":"38006",
#                "images":{
#                   "poster":"http:\/\/slurm.trakt.us\/images\/posters\/28701.jpg",
#                   "fanart":"http:\/\/slurm.trakt.us\/images\/fanart\/28701.jpg",
#                   "banner":"http:\/\/slurm.trakt.us\/images\/banners\/28701.jpg"
#                },
#                "ratings":{
#                   "percentage":45,
#                   "votes":2,
#                   "loved":0,
#                   "hated":2
#                },
#                "genres":[
#                   ""
#                ]
#             },
#             "episode":{
#                "season":1,
#                "number":8,
#                "title":"Vigilance",
#                "overview":"",
#                "url":"http:\/\/trakt.tv\/show\/saf3\/season\/1\/episode\/8",
#                "first_aired":1383984000,
#                "first_aired_iso":"2013-11-09T00:00:00-05:00",
#                "first_aired_localized":1383984000,
#                "first_aired_utc":1383973200,
#                "images":{
#                   "screen":"http:\/\/slurm.trakt.us\/images\/fanart\/28701-940.jpg"
#                },
#                "ratings":{
#                   "percentage":0,
#                   "votes":0,
#                   "loved":0,
#                   "hated":0
#                }
#             }
#          },
#          {
#             "show":{
#                "title":"The Thundermans",
#                "year":2013,
#                "url":"http:\/\/trakt.tv\/show\/the-thundermans",
#                "first_aired":1381809600,
#                "first_aired_iso":"2013-10-14T21:00:00-04:00",
#                "first_aired_localized":1381809600,
#                "first_aired_utc":1381798800,
#                "country":"United States",
#                "overview":"Meet The Thundermans, a typical suburban family that happens to have astounding superpowers. At the center of the action are the 14-year-old Thunderman twins, who share the same bathroom, the same school, and the same annoying little siblings. Their only difference? The sister is a super student with a super sunny disposition who super looks forward to being a superhero someday, and her twin brother is a super villain.",
#                "runtime":30,
#                "network":"Nickelodeon",
#                "air_day":"Monday",
#                "air_day_localized":"Monday",
#                "air_day_utc":"Monday",
#                "air_time":"9:00pm",
#                "air_time_localized":"9:00pm",
#                "air_time_utc":"6:00pm",
#                "certification":"",
#                "imdb_id":"tt2712516",
#                "tvdb_id":"274283",
#                "tvrage_id":"32627",
#                "images":{
#                   "poster":"http:\/\/slurm.trakt.us\/images\/posters\/29191.jpg",
#                   "fanart":"http:\/\/slurm.trakt.us\/images\/fanart\/29191.jpg",
#                   "banner":"http:\/\/slurm.trakt.us\/images\/banners\/29191.jpg"
#                },
#                "ratings":{
#                   "percentage":30,
#                   "votes":1,
#                   "loved":0,
#                   "hated":1
#                },
#                "genres":[
#                   "Comedy",
#                   "Family",
#                   "Science Fiction"
#                ]
#             },
#             "episode":{
#                "season":1,
#                "number":3,
#                "title":"Dinner Party",
#                "overview":"",
#                "url":"http:\/\/trakt.tv\/show\/the-thundermans\/season\/1\/episode\/3",
#                "first_aired":1384059600,
#                "first_aired_iso":"2013-11-09T21:00:00-05:00",
#                "first_aired_localized":1384059600,
#                "first_aired_utc":1384048800,
#                "images":{
#                   "screen":"http:\/\/slurm.trakt.us\/images\/fanart\/29191-940.jpg"
#                },
#                "ratings":{
#                   "percentage":0,
#                   "votes":0,
#                   "loved":0,
#                   "hated":0
#                }
#             }
#          }
#       ]
#    },
#    {
#       "id": '2',
#       "date":"2013-11-10",
#       "episodes":[
#          {
#             "show":{
#                "title":"When Ghosts Attack",
#                "year":2013,
#                "url":"http:\/\/trakt.tv\/show\/when-ghosts-attack",
#                "first_aired":0,
#                "first_aired_iso":"1969-12-31T16:00:00-05:00",
#                "first_aired_localized":0,
#                "first_aired_utc":-10800,
#                "country":"United States",
#                "overview":"Watch When Ghosts Attack, if you dare. Destination America's all-new series flickers to life just in time for Halloween season to expose what happens when an unseen, evil entity not only reveals itself to the living but strikes with terrifying force. In the eight-episode first season of When Ghosts Attack, travel to the dark side of the paranormal world, where poltergeist activity - like objects moving on their own - is child's play compared to the torment of a malevolent demon. Told from the first-person perspective of the victims and their loved ones, each episode uncovers multiple ghostly attacks. Hear first-hand what went through the victim's mind as their experience escalated from threatening whispers and dark omens to scratches, shoves, and the anguish of having to live alongside their invisible enemy. (Source: Destination America)",
#                "runtime":60,
#                "network":"Destination America",
#                "air_day":"Wednesday",
#                "air_day_localized":"Wednesday",
#                "air_day_utc":"Wednesday",
#                "air_time":"4:00pm",
#                "air_time_localized":"4:00pm",
#                "air_time_utc":"1:00pm",
#                "certification":"",
#                "imdb_id":"tt3205228",
#                "tvdb_id":"274535",
#                "tvrage_id":"37935",
#                "images":{
#                   "poster":"http:\/\/slurm.trakt.us\/images\/posters\/29349.jpg",
#                   "fanart":"http:\/\/slurm.trakt.us\/images\/fanart-dark.jpg",
#                   "banner":"http:\/\/slurm.trakt.us\/images\/banners\/29349.jpg"
#                },
#                "ratings":{
#                   "percentage":60,
#                   "votes":1,
#                   "loved":1,
#                   "hated":0
#                },
#                "genres":[
#                   ""
#                ]
#             },
#             "episode":{
#                "season":1,
#                "number":4,
#                "title":"Attack from the Past",
#                "overview":"When a family gets the opportunity to move to scenic Frederick, Md., they jump at the chance. Little do they know they are moving in with evil entities that will do anything to scare them away. When the macabre presence violently threatens a priest, the family fears the vicious spirits will kill them.\n\nOver in Gloucester, Va., Brian Schiff and three friends discover an eerie, abandoned house with a local legend. When the door opens and creepily beckons them in, the friends are not prepared for the terrifying attack that plagues them.\n\nA Winchester, Va., estate with more than 150 years of history has its owners terrified and fearing for their safety after a ghost investigator experiences a violent encounter. ",
#                "url":"http:\/\/trakt.tv\/show\/when-ghosts-attack\/season\/1\/episode\/4",
#                "first_aired":0,
#                "first_aired_iso":"1969-12-31T16:00:00-05:00",
#                "first_aired_localized":0,
#                "first_aired_utc":-10800,
#                "images":{
#                   "screen":"http:\/\/slurm.trakt.us\/images\/episode-dark.jpg"
#                },
#                "ratings":{
#                   "percentage":0,
#                   "votes":0,
#                   "loved":0,
#                   "hated":0
#                }
#             }
#          },
#          {
#             "show":{
#                "title":"Shake It Up",
#                "year":2010,
#                "url":"http:\/\/trakt.tv\/show\/shake-it-up",
#                "first_aired":1289183400,
#                "first_aired_iso":"2010-11-07T18:30:00-05:00",
#                "first_aired_localized":1289183400,
#                "first_aired_utc":1289172600,
#                "country":"United States",
#                "overview":"Best friends CeCe Jones and Rachel \"Rocky\" Blue have dreamed about becoming professional dancers ever since they were little girls. Their big break finally comes when the girls land roles as backup dancers on a local Chicago TV dance show, \"Shake It Up, Chicago!\". As the girls pop, lock, and learn challenging dance moves for each week's show, they revel in their newfound status but also quickly learn they'll need more than fancy footwork to match wits with the show's other dancers, notably the highly competitive siblings Gunther and Tinka. At the same time, with their best friend Deuce and Rocky's brother Ty, they must quickstep through the complex twists and turns of an average big-city high school as well as Windy City family life, including their obligation to babysit CeCe's mischievous younger brother, Flynn.",
#                "runtime":30,
#                "network":"Disney Channel",
#                "air_day":"Sunday",
#                "air_day_localized":"Sunday",
#                "air_day_utc":"Sunday",
#                "air_time":"6:30pm",
#                "air_time_localized":"6:30pm",
#                "air_time_utc":"3:30pm",
#                "certification":"TV-G",
#                "imdb_id":"tt1661326",
#                "tvdb_id":"205251",
#                "tvrage_id":"25778",
#                "images":{
#                   "poster":"http:\/\/slurm.trakt.us\/images\/posters\/759.jpg",
#                   "fanart":"http:\/\/slurm.trakt.us\/images\/fanart\/759.jpg",
#                   "banner":"http:\/\/slurm.trakt.us\/images\/banners\/759.jpg"
#                },
#                "ratings":{
#                   "percentage":68,
#                   "votes":25,
#                   "loved":18,
#                   "hated":7
#                },
#                "genres":[
#                   "Comedy",
#                   "Family"
#                ]
#             },
#             "episode":{
#                "season":3,
#                "number":26,
#                "title":"Remember Me",
#                "overview":"In the series finale, \"Shake It Up Chicago\" hosts a charity fashion show with Rocky, Tinka and CeCe as its star models, however the girls' runway dreams are cut short when a fashion mishap leaves CeCe with amnesia. While Georgia and Flynn try to follow the doctor's orders and give CeCe time to heal, a devastated Rocky tries everything she can to get her best friend to remember her and the special memories they shared.",
#                "url":"http:\/\/trakt.tv\/show\/shake-it-up\/season\/3\/episode\/26",
#                "first_aired":1384137000,
#                "first_aired_iso":"2013-11-10T18:30:00-05:00",
#                "first_aired_localized":1384137000,
#                "first_aired_utc":1384126200,
#                "images":{
#                   "screen":"http:\/\/slurm.trakt.us\/images\/episodes\/759-3-26.jpg"
#                },
#                "ratings":{
#                   "percentage":0,
#                   "votes":0,
#                   "loved":0,
#                   "hated":0
#                }
#             }
#          },
#          {
#             "show":{
#                "title":"Once Upon A Time (2011)",
#                "year":2011,
#                "url":"http:\/\/trakt.tv\/show\/once-upon-a-time-2011",
#                "first_aired":1319425200,
#                "first_aired_iso":"2011-10-23T20:00:00-04:00",
#                "first_aired_localized":1319425200,
#                "first_aired_utc":1319414400,
#                "country":"United States",
#                "overview":"Emma Swan, a 28-year-old bail bonds collector, has always been a fiercely independent person since being abandoned as a baby. Her son Henry, who she gave up for adoption years ago, finds and tries to convince Emma that she is Snow White's missing daughter. Henry shows Emma that in the fairytale, Prince Charming and Snow White sent her away to protect her. Emma doesn't believe him and takes Henry back to Storybrooke...",
#                "runtime":60,
#                "network":"ABC",
#                "air_day":"Sunday",
#                "air_day_localized":"Sunday",
#                "air_day_utc":"Sunday",
#                "air_time":"8:00pm",
#                "air_time_localized":"8:00pm",
#                "air_time_utc":"5:00pm",
#                "certification":"TV-PG",
#                "imdb_id":"tt1843230",
#                "tvdb_id":"248835",
#                "tvrage_id":"28385",
#                "images":{
#                   "poster":"http:\/\/slurm.trakt.us\/images\/posters\/10646.15.jpg",
#                   "fanart":"http:\/\/slurm.trakt.us\/images\/fanart\/10646.15.jpg",
#                   "banner":"http:\/\/slurm.trakt.us\/images\/banners\/10646.15.jpg"
#                },
#                "ratings":{
#                   "percentage":81,
#                   "votes":4421,
#                   "loved":4027,
#                   "hated":394
#                },
#                "genres":[
#                   "Drama",
#                   "Fantasy"
#                ]
#             },
#             "episode":{
#                "season":3,
#                "number":7,
#                "title":"Dark Hollow",
#                "overview":"Mr. Gold and Regina send Ariel back to Storybrooke with an item that will allow Belle to locate a hidden artifact that could help take down Pan. But unbeknownst to them, two men have broken into the town with the intent to stop them \u2013 at all costs. Meanwhile, Emma, Neal and Hook attempt to find Dark Hollow, where Peter Pan\u2019s shadow dwells, in order to capture it, and Mary Margaret is upset with David for keeping his poisoning a secret from her. ",
#                "url":"http:\/\/trakt.tv\/show\/once-upon-a-time-2011\/season\/3\/episode\/7",
#                "first_aired":1384142400,
#                "first_aired_iso":"2013-11-10T20:00:00-05:00",
#                "first_aired_localized":1384142400,
#                "first_aired_utc":1384131600,
#                "images":{
#                   "screen":"http:\/\/slurm.trakt.us\/images\/episodes\/10646-3-7.15.jpg"
#                },
#                "ratings":{
#                   "percentage":100,
#                   "votes":4,
#                   "loved":4,
#                   "hated":0
#                }
#             }
#          },
#          {
#             "show":{
#                "title":"See Dad Run",
#                "year":2012,
#                "url":"http:\/\/trakt.tv\/show\/see-dad-run",
#                "first_aired":1349578800,
#                "first_aired_iso":"2012-10-06T20:00:00-04:00",
#                "first_aired_localized":1349578800,
#                "first_aired_utc":1349568000,
#                "country":"United States",
#                "overview":"\"See Dad Run\" tells the story of David Hobbs (Scott Baio), who has spent the last decade playing the perfect father on one of TV\u2019s biggest sitcoms. But when the series ends and his wife resumes her own television career, he finds himself cast in his most challenging role to date: handling the day-to-day needs of three kids who\u2019ve grown accustomed to not having him around. David soon learns that playing a dad on TV is child\u2019s play compared to the real thing.",
#                "runtime":30,
#                "network":"Nick at Nite",
#                "air_day":"Saturday",
#                "air_day_localized":"Saturday",
#                "air_day_utc":"Saturday",
#                "air_time":"8:00pm",
#                "air_time_localized":"8:00pm",
#                "air_time_utc":"5:00pm",
#                "certification":"TV-PG",
#                "imdb_id":"tt2382108",
#                "tvdb_id":"262266",
#                "tvrage_id":"32703",
#                "images":{
#                   "poster":"http:\/\/slurm.trakt.us\/images\/posters\/18869.jpg",
#                   "fanart":"http:\/\/slurm.trakt.us\/images\/fanart\/18869.jpg",
#                   "banner":"http:\/\/slurm.trakt.us\/images\/banners\/18869.jpg"
#                },
#                "ratings":{
#                   "percentage":62,
#                   "votes":17,
#                   "loved":14,
#                   "hated":3
#                },
#                "genres":[
#                   "Comedy"
#                ]
#             },
#             "episode":{
#                "season":2,
#                "number":11,
#                "title":"See Dad See Dad Run",
#                "overview":"",
#                "url":"http:\/\/trakt.tv\/show\/see-dad-run\/season\/2\/episode\/11",
#                "first_aired":1384142400,
#                "first_aired_iso":"2013-11-10T20:00:00-05:00",
#                "first_aired_localized":1384142400,
#                "first_aired_utc":1384131600,
#                "images":{
#                   "screen":"http:\/\/slurm.trakt.us\/images\/fanart\/18869-940.jpg"
#                },
#                "ratings":{
#                   "percentage":0,
#                   "votes":0,
#                   "loved":0,
#                   "hated":0
#                }
#             }
#          },
#          {
#             "show":{
#                "title":"Austin & Ally",
#                "year":2011,
#                "url":"http:\/\/trakt.tv\/show\/austin-and-ally",
#                "first_aired":1322886600,
#                "first_aired_iso":"2011-12-02T20:30:00-05:00",
#                "first_aired_localized":1322886600,
#                "first_aired_utc":1322875800,
#                "country":"United States",
#                "overview":"A comedy about the unique relationship between a young songwriter, Ally Dawson, and Austin Moon, the overnight internet sensation who gains sudden notoriety after performing one of Ally's songs. Austin and Ally struggle with how to maintain and capitalize on Austin's newfound fame. Austin is more of a rebel type who doesn't follow the rules and is somewhat immature for his age, while Ally is conservative yet self-conscious.",
#                "runtime":30,
#                "network":"Disney Channel",
#                "air_day":"Friday",
#                "air_day_localized":"Friday",
#                "air_day_utc":"Friday",
#                "air_time":"8:30pm",
#                "air_time_localized":"8:30pm",
#                "air_time_utc":"5:30pm",
#                "certification":"TV-G",
#                "imdb_id":"tt1830491",
#                "tvdb_id":"254245",
#                "tvrage_id":"29965",
#                "images":{
#                   "poster":"http:\/\/slurm.trakt.us\/images\/posters\/13377.jpg",
#                   "fanart":"http:\/\/slurm.trakt.us\/images\/fanart\/13377.jpg",
#                   "banner":"http:\/\/slurm.trakt.us\/images\/banners\/13377.jpg"
#                },
#                "ratings":{
#                   "percentage":86,
#                   "votes":19,
#                   "loved":17,
#                   "hated":2
#                },
#                "genres":[
#                   "Comedy"
#                ]
#             },
#             "episode":{
#                "season":3,
#                "number":3,
#                "title":"Presidents & Problems",
#                "overview":"Following the last show of Austin\u2019s tour, the gang does some sight-seeing at a Washington D.C. museum, where Austin accidentally gets stuck to a priceless object and must find a way to return it before performing for the President.",
#                "url":"http:\/\/trakt.tv\/show\/austin-and-ally\/season\/3\/episode\/3",
#                "first_aired":1384144200,
#                "first_aired_iso":"2013-11-10T20:30:00-05:00",
#                "first_aired_localized":1384144200,
#                "first_aired_utc":1384133400,
#                "images":{
#                   "screen":"http:\/\/slurm.trakt.us\/images\/fanart\/13377-940.jpg"
#                },
#                "ratings":{
#                   "percentage":0,
#                   "votes":0,
#                   "loved":0,
#                   "hated":0
#                }
#             }
#          },
#          {
#             "show":{
#                "title":"Instant Mom",
#                "year":2013,
#                "url":"http:\/\/trakt.tv\/show\/instant-mom",
#                "first_aired":1380511800,
#                "first_aired_iso":"2013-09-29T20:30:00-04:00",
#                "first_aired_localized":1380511800,
#                "first_aired_utc":1380501000,
#                "country":"United States",
#                "overview":"\"Instant Mom\" follows young party girl Stephanie who trades in cosmos for carpools when she marries an older man, Charlie, with three kids. Stephanie slowly grows into her role as a full-time stepmom while struggling to maintain some sense of her fun-loving, slightly irresponsible life.",
#                "runtime":30,
#                "network":"Nick at Nite",
#                "air_day":"Sunday",
#                "air_day_localized":"Sunday",
#                "air_day_utc":"Sunday",
#                "air_time":"8:30pm",
#                "air_time_localized":"8:30pm",
#                "air_time_utc":"5:30pm",
#                "certification":"",
#                "imdb_id":"tt2545498",
#                "tvdb_id":"269935",
#                "tvrage_id":"32519",
#                "images":{
#                   "poster":"http:\/\/slurm.trakt.us\/images\/poster-dark.2.jpg",
#                   "fanart":"http:\/\/slurm.trakt.us\/images\/fanart\/28880.2.jpg",
#                   "banner":"http:\/\/slurm.trakt.us\/images\/banners\/28880.2.jpg"
#                },
#                "ratings":{
#                   "percentage":90,
#                   "votes":1,
#                   "loved":1,
#                   "hated":0
#                },
#                "genres":[
#                   "Comedy"
#                ]
#             },
#             "episode":{
#                "season":1,
#                "number":7,
#                "title":"Dances with She-Wolves",
#                "overview":"Stephanie attempts to get more involved by participating on the parents\u2019 dance committee at James\u2019 school only to find the other mothers mean and unwelcoming to the too pretty, too excited, binder-ready Stephanie.",
#                "url":"http:\/\/trakt.tv\/show\/instant-mom\/season\/1\/episode\/7",
#                "first_aired":1384144200,
#                "first_aired_iso":"2013-11-10T20:30:00-05:00",
#                "first_aired_localized":1384144200,
#                "first_aired_utc":1384133400,
#                "images":{
#                   "screen":"http:\/\/slurm.trakt.us\/images\/fanart\/28880-940.2.jpg"
#                },
#                "ratings":{
#                   "percentage":0,
#                   "votes":0,
#                   "loved":0,
#                   "hated":0
#                }
#             }
#          },
#          {
#             "show":{
#                "title":"Boardwalk Empire",
#                "year":2010,
#                "url":"http:\/\/trakt.tv\/show\/boardwalk-empire",
#                "first_aired":1284955200,
#                "first_aired_iso":"2010-09-19T21:00:00-04:00",
#                "first_aired_localized":1284955200,
#                "first_aired_utc":1284944400,
#                "country":"United States",
#                "overview":"Boardwalk Empire is a period drama focusing on Enoch \"Nucky\" Thompson (based on the historical Enoch L. Johnson), a political figure who rose to prominence and controlled Atlantic City, New Jersey, during the Prohibition period of the 1920s and 1930s. Nucky interacts with several historical figures in both his personal and political life, including mobsters, politicians, government agents, and the common folk who look up to him. The federal government also takes an interest in the bootlegging and other illegal activities in the area, sending agents to investigate possible mob connections but also looking at Nucky's lifestyle\u2014expensive and lavish for a county political figure.",
#                "runtime":60,
#                "network":"HBO",
#                "air_day":"Sunday",
#                "air_day_localized":"Sunday",
#                "air_day_utc":"Sunday",
#                "air_time":"9:00pm",
#                "air_time_localized":"9:00pm",
#                "air_time_utc":"6:00pm",
#                "certification":"TV-MA",
#                "imdb_id":"tt0979432",
#                "tvdb_id":"84947",
#                "tvrage_id":"23561",
#                "images":{
#                   "poster":"http:\/\/slurm.trakt.us\/images\/posters\/121.13.jpg",
#                   "fanart":"http:\/\/slurm.trakt.us\/images\/fanart\/121.13.jpg",
#                   "banner":"http:\/\/slurm.trakt.us\/images\/banners\/121.13.jpg"
#                },
#                "ratings":{
#                   "percentage":89,
#                   "votes":3122,
#                   "loved":3028,
#                   "hated":94
#                },
#                "genres":[
#                   "Drama",
#                   "Crime"
#                ]
#             },
#             "episode":{
#                "season":4,
#                "number":10,
#                "title":"White Horse Pike",
#                "overview":"Tipped off by Sally Wheet, Nucky enlists Eli and Agent Knox to check out the extra cargo in Florida shipments. Margaret ponders a deal with Rothstein to improve her family\u2019s living conditions. Capone grows suspicious of Torrio; Nucky faces a dilemma; Eli makes peace with Willie.",
#                "url":"http:\/\/trakt.tv\/show\/boardwalk-empire\/season\/4\/episode\/10",
#                "first_aired":1384146000,
#                "first_aired_iso":"2013-11-10T21:00:00-05:00",
#                "first_aired_localized":1384146000,
#                "first_aired_utc":1384135200,
#                "images":{
#                   "screen":"http:\/\/slurm.trakt.us\/images\/episodes\/121-4-10.13.jpg"
#                },
#                "ratings":{
#                   "percentage":70,
#                   "votes":1,
#                   "loved":1,
#                   "hated":0
#                }
#             }
#          },
#          {
#             "show":{
#                "title":"Homeland",
#                "year":2011,
#                "url":"http:\/\/trakt.tv\/show\/homeland",
#                "first_aired":1317614400,
#                "first_aired_iso":"2011-10-02T21:00:00-04:00",
#                "first_aired_localized":1317614400,
#                "first_aired_utc":1317603600,
#                "country":"United States",
#                "overview":"While in Iraq, Carrie Mathison, a Central Intelligence Agency operations officer, had been warned by an asset that an American prisoner of war had been turned by al-Qaeda.  After conducting an unauthorized operation in Iraq, Carrie is put on probation and reassigned to the CIA's Counter-terrorism Center in Langley, Virginia.",
#                "runtime":60,
#                "network":"Showtime",
#                "air_day":"Sunday",
#                "air_day_localized":"Sunday",
#                "air_day_utc":"Sunday",
#                "air_time":"9:00pm",
#                "air_time_localized":"9:00pm",
#                "air_time_utc":"6:00pm",
#                "certification":"TV-MA",
#                "imdb_id":"tt1796960",
#                "tvdb_id":"247897",
#                "tvrage_id":"27811",
#                "images":{
#                   "poster":"http:\/\/slurm.trakt.us\/images\/posters\/10369.16.jpg",
#                   "fanart":"http:\/\/slurm.trakt.us\/images\/fanart\/10369.16.jpg",
#                   "banner":"http:\/\/slurm.trakt.us\/images\/banners\/10369.16.jpg"
#                },
#                "ratings":{
#                   "percentage":89,
#                   "votes":7010,
#                   "loved":6818,
#                   "hated":192
#                },
#                "genres":[
#                   "Drama",
#                   "Suspense",
#                   "Thriller"
#                ]
#             },
#             "episode":{
#                "season":3,
#                "number":7,
#                "title":"Gerontion",
#                "overview":"Saul makes the gamble of his career; Carrie and Quinn try to contain a local police investigation; Mira's marriage is at a crossroads.",
#                "url":"http:\/\/trakt.tv\/show\/homeland\/season\/3\/episode\/7",
#                "first_aired":1384146000,
#                "first_aired_iso":"2013-11-10T21:00:00-05:00",
#                "first_aired_localized":1384146000,
#                "first_aired_utc":1384135200,
#                "images":{
#                   "screen":"http:\/\/slurm.trakt.us\/images\/episodes\/10369-3-7.16.jpg"
#                },
#                "ratings":{
#                   "percentage":57,
#                   "votes":3,
#                   "loved":2,
#                   "hated":1
#                }
#             }
#          },
#          {
#             "show":{
#                "title":"Revenge",
#                "year":2011,
#                "url":"http:\/\/trakt.tv\/show\/revenge",
#                "first_aired":1316577600,
#                "first_aired_iso":"2011-09-20T21:00:00-04:00",
#                "first_aired_localized":1316577600,
#                "first_aired_utc":1316566800,
#                "country":"United States",
#                "overview":"Emily Thorne rents a house in the Hamptons for the summer, seemingly intent on nothing more than enjoying a break in the popular resort. But it soon becomes clear that there's more to her visit. Her real name is Amanda Clarke and her father was framed for a crime he didn't commit and sent to prison for life and she has come to the Hamptons to seek revenge against the people who betrayed him and saw him sent to jail.",
#                "runtime":60,
#                "network":"ABC",
#                "air_day":"Tuesday",
#                "air_day_localized":"Tuesday",
#                "air_day_utc":"Tuesday",
#                "air_time":"9:00pm",
#                "air_time_localized":"9:00pm",
#                "air_time_utc":"6:00pm",
#                "certification":"TV-14",
#                "imdb_id":"tt1837642",
#                "tvdb_id":"248837",
#                "tvrage_id":"28387",
#                "images":{
#                   "poster":"http:\/\/slurm.trakt.us\/images\/posters\/10257.39.jpg",
#                   "fanart":"http:\/\/slurm.trakt.us\/images\/fanart\/10257.39.jpg",
#                   "banner":"http:\/\/slurm.trakt.us\/images\/banners\/10257.39.jpg"
#                },
#                "ratings":{
#                   "percentage":83,
#                   "votes":2702,
#                   "loved":2487,
#                   "hated":215
#                },
#                "genres":[
#                   "Drama"
#                ]
#             },
#             "episode":{
#                "season":3,
#                "number":7,
#                "title":"Resurgence",
#                "overview":"Conrad hires famed party-girl turned PR mastermind Bizzy Preston to restore the Grayson family name, while Emily sinks her teeth deeper into her plan and Nolan has a revenge-agenda of his own.",
#                "url":"http:\/\/trakt.tv\/show\/revenge\/season\/3\/episode\/7",
#                "first_aired":1384146000,
#                "first_aired_iso":"2013-11-10T21:00:00-05:00",
#                "first_aired_localized":1384146000,
#                "first_aired_utc":1384135200,
#                "images":{
#                   "screen":"http:\/\/slurm.trakt.us\/images\/episodes\/10257-3-7.39.jpg"
#                },
#                "ratings":{
#                   "percentage":0,
#                   "votes":0,
#                   "loved":0,
#                   "hated":0
#                }
#             }
#          },
#          {
#             "show":{
#                "title":"The Good Wife",
#                "year":2009,
#                "url":"http:\/\/trakt.tv\/show\/the-good-wife",
#                "first_aired":1253678400,
#                "first_aired_iso":"2009-09-22T21:00:00-04:00",
#                "first_aired_localized":1253678400,
#                "first_aired_utc":1253667600,
#                "country":"United States",
#                "overview":"The Good Wife is a drama starring Emmy Award winner Julianna Margulies as a wife and mother who must assume full responsibility for her family and re-enter the workforce after her husband's very public sex and political corruption scandal lands him in jail.",
#                "runtime":60,
#                "network":"CBS",
#                "air_day":"Tuesday",
#                "air_day_localized":"Tuesday",
#                "air_day_utc":"Tuesday",
#                "air_time":"9:00pm",
#                "air_time_localized":"9:00pm",
#                "air_time_utc":"6:00pm",
#                "certification":"TV-14",
#                "imdb_id":"tt1442462",
#                "tvdb_id":"95451",
#                "tvrage_id":"22755",
#                "images":{
#                   "poster":"http:\/\/slurm.trakt.us\/images\/posters\/338.5.jpg",
#                   "fanart":"http:\/\/slurm.trakt.us\/images\/fanart\/338.5.jpg",
#                   "banner":"http:\/\/slurm.trakt.us\/images\/banners\/338.5.jpg"
#                },
#                "ratings":{
#                   "percentage":87,
#                   "votes":1328,
#                   "loved":1252,
#                   "hated":76
#                },
#                "genres":[
#                   "Drama"
#                ]
#             },
#             "episode":{
#                "season":5,
#                "number":7,
#                "title":"The Next Week",
#                "overview":"Zach makes a discovery that leads Alicia and Cary to believe that the Lockhart\/Gardner firm is spying on them; Will helps one of Alicia's former clients; Clarke Hayden (Nathan Lane) offers financial advice to Florrick\/Agos.",
#                "url":"http:\/\/trakt.tv\/show\/the-good-wife\/season\/5\/episode\/7",
#                "first_aired":1384146000,
#                "first_aired_iso":"2013-11-10T21:00:00-05:00",
#                "first_aired_localized":1384146000,
#                "first_aired_utc":1384135200,
#                "images":{
#                   "screen":"http:\/\/slurm.trakt.us\/images\/fanart\/338-940.5.jpg"
#                },
#                "ratings":{
#                   "percentage":90,
#                   "votes":2,
#                   "loved":2,
#                   "hated":0
#                }
#             }
#          },
#          {
#             "show":{
#                "title":"The Walking Dead",
#                "year":2010,
#                "url":"http:\/\/trakt.tv\/show\/the-walking-dead",
#                "first_aired":1288584000,
#                "first_aired_iso":"2010-10-31T21:00:00-04:00",
#                "first_aired_localized":1288584000,
#                "first_aired_utc":1288573200,
#                "country":"United States",
#                "overview":"Based on the comic book series of the same name, The Walking Dead tells the story of a small group of survivors living in the aftermath of a zombie apocalypse.",
#                "runtime":60,
#                "network":"AMC",
#                "air_day":"Sunday",
#                "air_day_localized":"Sunday",
#                "air_day_utc":"Sunday",
#                "air_time":"9:00pm",
#                "air_time_localized":"9:00pm",
#                "air_time_utc":"6:00pm",
#                "certification":"TV-14",
#                "imdb_id":"tt1520211",
#                "tvdb_id":"153021",
#                "tvrage_id":"25056",
#                "images":{
#                   "poster":"http:\/\/slurm.trakt.us\/images\/posters\/124.25.jpg",
#                   "fanart":"http:\/\/slurm.trakt.us\/images\/fanart\/124.25.jpg",
#                   "banner":"http:\/\/slurm.trakt.us\/images\/banners\/124.25.jpg"
#                },
#                "ratings":{
#                   "percentage":89,
#                   "votes":13168,
#                   "loved":12607,
#                   "hated":561
#                },
#                "genres":[
#                   "Drama",
#                   "Horror",
#                   "Suspense"
#                ]
#             },
#             "episode":{
#                "season":4,
#                "number":5,
#                "title":"Internment",
#                "overview":"Assorted enemies pressure Rick and the group; the survivors and the prison may reach a breaking point.",
#                "url":"http:\/\/trakt.tv\/show\/the-walking-dead\/season\/4\/episode\/5",
#                "first_aired":1384146000,
#                "first_aired_iso":"2013-11-10T21:00:00-05:00",
#                "first_aired_localized":1384146000,
#                "first_aired_utc":1384135200,
#                "images":{
#                   "screen":"http:\/\/slurm.trakt.us\/images\/episodes\/124-4-5.25.jpg"
#                },
#                "ratings":{
#                   "percentage":83,
#                   "votes":11,
#                   "loved":10,
#                   "hated":1
#                }
#             }
#          },
#          {
#             "show":{
#                "title":"Betrayal",
#                "year":2013,
#                "url":"http:\/\/trakt.tv\/show\/betrayal",
#                "first_aired":1380517200,
#                "first_aired_iso":"2013-09-29T22:00:00-04:00",
#                "first_aired_localized":1380517200,
#                "first_aired_utc":1380506400,
#                "country":"United States",
#                "overview":"A chance meeting leads photographer Sara Hadley and Attorney Jack McAllister to an undeniable instant attraction.  Sara\u2019s husband Drew is a successful prosecutor with political aspirations.  Jack is married to Elaine the daughter of his boss Thacher Karsten.  When Karsten's brother-in-law Lou is murdered, all evidence points to Karsten\u2019s son T.J. Jack, the company\u2019s lead council, will have to defend him.  For Sara\u2019s prosecutor husband Drew, this is the kind of high-profile murder case that can secure his political future.  Just as Sara and Jack\u2019s affair is starting, the lovers will find themselves in an impossible situation\u2013on opposite sides of a murder investigation.",
#                "runtime":60,
#                "network":"ABC",
#                "air_day":"Sunday",
#                "air_day_localized":"Sunday",
#                "air_day_utc":"Sunday",
#                "air_time":"10:00pm",
#                "air_time_localized":"10:00pm",
#                "air_time_utc":"7:00pm",
#                "certification":"",
#                "imdb_id":"tt2751074",
#                "tvdb_id":"269647",
#                "tvrage_id":"34645",
#                "images":{
#                   "poster":"http:\/\/slurm.trakt.us\/images\/posters\/23283.5.jpg",
#                   "fanart":"http:\/\/slurm.trakt.us\/images\/fanart\/23283.5.jpg",
#                   "banner":"http:\/\/slurm.trakt.us\/images\/banners\/23283.5.jpg"
#                },
#                "ratings":{
#                   "percentage":59,
#                   "votes":37,
#                   "loved":23,
#                   "hated":14
#                },
#                "genres":[
#                   "Drama"
#                ]
#             },
#             "episode":{
#                "season":1,
#                "number":7,
#                "title":"We Are Not Going To Baileys Harbor",
#                "overview":"Neither Sara nor Jack's families will ever be the same after Drew's discovery of the affair. As Sara and Jack attempt to navigate their newly fractured relationships with their spouses and children, Elaine seeks support from an unlikely source. Meanwhile, a despondent Drew discovers information that could reopen Lou Mrozek\u2018s murder investigation, and Zarek, anxious to please Karsten, resorts to drastic measures to deal with Brandy.",
#                "url":"http:\/\/trakt.tv\/show\/betrayal\/season\/1\/episode\/7",
#                "first_aired":1384149600,
#                "first_aired_iso":"2013-11-10T22:00:00-05:00",
#                "first_aired_localized":1384149600,
#                "first_aired_utc":1384138800,
#                "images":{
#                   "screen":"http:\/\/slurm.trakt.us\/images\/fanart\/23283-940.5.jpg"
#                },
#                "ratings":{
#                   "percentage":0,
#                   "votes":0,
#                   "loved":0,
#                   "hated":0
#                }
#             }
#          },
#          {
#             "show":{
#                "title":"Eastbound & Down",
#                "year":2009,
#                "url":"http:\/\/trakt.tv\/show\/eastbound-and-down",
#                "first_aired":1234764000,
#                "first_aired_iso":"2009-02-15T22:00:00-05:00",
#                "first_aired_localized":1234764000,
#                "first_aired_utc":1234753200,
#                "country":"United States",
#                "overview":"Relief Pitcher Kenny Powers was poised to rule the Big Leagues, but two things got in his way: his fading fastball and his insufferable personality.  After a spectacular career flame-out, Kenny came home to Shelby, NC and picked up a job as a substitute gym teacher (mostly so his brother Dustin would stop threatening to kick him out).  He's spent every moment since then cashing in the last of his dying fame while plotting his inevitable comeback...one beer at a time.",
#                "runtime":30,
#                "network":"HBO",
#                "air_day":"Sunday",
#                "air_day_localized":"Sunday",
#                "air_day_utc":"Sunday",
#                "air_time":"10:00pm",
#                "air_time_localized":"10:00pm",
#                "air_time_utc":"7:00pm",
#                "certification":"TV-MA",
#                "imdb_id":"tt0866442",
#                "tvdb_id":"82467",
#                "tvrage_id":"21051",
#                "images":{
#                   "poster":"http:\/\/slurm.trakt.us\/images\/posters\/110.jpg",
#                   "fanart":"http:\/\/slurm.trakt.us\/images\/fanart\/110.jpg",
#                   "banner":"http:\/\/slurm.trakt.us\/images\/banners\/110.jpg"
#                },
#                "ratings":{
#                   "percentage":84,
#                   "votes":683,
#                   "loved":628,
#                   "hated":55
#                },
#                "genres":[
#                   "Comedy"
#                ]
#             },
#             "episode":{
#                "season":4,
#                "number":7,
#                "title":"Chapter 28",
#                "overview":"Kenny's personal life takes a toll on his work; Stevie keeps up appearances in the face of adversity; Kenny learns a valuable Christmas lesson. ",
#                "url":"http:\/\/trakt.tv\/show\/eastbound-and-down\/season\/4\/episode\/7",
#                "first_aired":1384149600,
#                "first_aired_iso":"2013-11-10T22:00:00-05:00",
#                "first_aired_localized":1384149600,
#                "first_aired_utc":1384138800,
#                "images":{
#                   "screen":"http:\/\/slurm.trakt.us\/images\/fanart\/110-940.jpg"
#                },
#                "ratings":{
#                   "percentage":0,
#                   "votes":0,
#                   "loved":0,
#                   "hated":0
#                }
#             }
#          },
#          {
#             "show":{
#                "title":"Masters of Sex",
#                "year":2013,
#                "url":"http:\/\/trakt.tv\/show\/masters-of-sex",
#                "first_aired":1380517200,
#                "first_aired_iso":"2013-09-29T22:00:00-04:00",
#                "first_aired_localized":1380517200,
#                "first_aired_utc":1380506400,
#                "country":"United States",
#                "overview":"MASTERS OF SEX stars Michael Sheen and Lizzy Caplan, who will portray the real-life pioneers of the science of human sexuality, William Masters and Virginia Johnson. The series chronicles the unusual lives, romance and pop culture trajectory of Masters and Johnson. Their research touched off the sexual revolution and took them from a mid-western teaching hospital in St. Louis to the cover of Time magazine.",
#                "runtime":60,
#                "network":"Showtime",
#                "air_day":"Sunday",
#                "air_day_localized":"Sunday",
#                "air_day_utc":"Sunday",
#                "air_time":"10:00pm",
#                "air_time_localized":"10:00pm",
#                "air_time_utc":"7:00pm",
#                "certification":"TV-MA",
#                "imdb_id":"tt2137109",
#                "tvdb_id":"261557",
#                "tvrage_id":"32002",
#                "images":{
#                   "poster":"http:\/\/slurm.trakt.us\/images\/posters\/19038.1.jpg",
#                   "fanart":"http:\/\/slurm.trakt.us\/images\/fanart\/19038.1.jpg",
#                   "banner":"http:\/\/slurm.trakt.us\/images\/banners\/19038.1.jpg"
#                },
#                "ratings":{
#                   "percentage":80,
#                   "votes":154,
#                   "loved":142,
#                   "hated":12
#                },
#                "genres":[
#                   "Drama"
#                ]
#             },
#             "episode":{
#                "season":1,
#                "number":7,
#                "title":"All Together Now",
#                "overview":"Masters and Johnson continue their sexual response study \u2013 now as participants \u2013 but Johnson fears their work may be interfering with Masters\u2019 home life. Libby pressures Dr. Haas to resume her fertility treatments in secret. Meanwhile, Haas struggles to let go of feelings for Virginia as his relationship with Vivian deepens. And Margaret Scully, caught in her infidelity, confronts her husband on the mounting problems in their marriage.",
#                "url":"http:\/\/trakt.tv\/show\/masters-of-sex\/season\/1\/episode\/7",
#                "first_aired":1384149600,
#                "first_aired_iso":"2013-11-10T22:00:00-05:00",
#                "first_aired_localized":1384149600,
#                "first_aired_utc":1384138800,
#                "images":{
#                   "screen":"http:\/\/slurm.trakt.us\/images\/episodes\/19038-1-7.1.jpg"
#                },
#                "ratings":{
#                   "percentage":70,
#                   "votes":2,
#                   "loved":2,
#                   "hated":0
#                }
#             }
#          },
#          {
#             "show":{
#                "title":"Witches of East End",
#                "year":2013,
#                "url":"http:\/\/trakt.tv\/show\/witches-of-east-end",
#                "first_aired":1381122000,
#                "first_aired_iso":"2013-10-06T22:00:00-04:00",
#                "first_aired_localized":1381122000,
#                "first_aired_utc":1381111200,
#                "country":"United States",
#                "overview":"Based on Melissa de la Cruz's best-selling novel, \"Witches of East End\" centers on the adventures of Joanna Beauchamp and her two adult daughters Freya and Ingrid -- both of whom unknowingly are their family's next generation of witches -- who lead seemingly quiet, uneventful modern day lives in Long Island's secluded seaside town of East Haven. When Freya becomes engaged to a young, wealthy newcomer, a series of events forces Joanna to admit to her daughters they are, in fact, powerful and immortal witches.",
#                "runtime":60,
#                "network":"Lifetime",
#                "air_day":"Sunday",
#                "air_day_localized":"Sunday",
#                "air_day_utc":"Sunday",
#                "air_time":"10:00pm",
#                "air_time_localized":"10:00pm",
#                "air_time_utc":"7:00pm",
#                "certification":"",
#                "imdb_id":"tt2288064",
#                "tvdb_id":"267259",
#                "tvrage_id":"32887",
#                "images":{
#                   "poster":"http:\/\/slurm.trakt.us\/images\/posters\/23335.1.jpg",
#                   "fanart":"http:\/\/slurm.trakt.us\/images\/fanart\/23335.1.jpg",
#                   "banner":"http:\/\/slurm.trakt.us\/images\/banners\/23335.1.jpg"
#                },
#                "ratings":{
#                   "percentage":79,
#                   "votes":94,
#                   "loved":88,
#                   "hated":6
#                },
#                "genres":[
#                   "Drama"
#                ]
#             },
#             "episode":{
#                "season":1,
#                "number":6,
#                "title":"Potentia Noctis",
#                "overview":"",
#                "url":"http:\/\/trakt.tv\/show\/witches-of-east-end\/season\/1\/episode\/6",
#                "first_aired":1384149600,
#                "first_aired_iso":"2013-11-10T22:00:00-05:00",
#                "first_aired_localized":1384149600,
#                "first_aired_utc":1384138800,
#                "images":{
#                   "screen":"http:\/\/slurm.trakt.us\/images\/fanart\/23335-940.1.jpg"
#                },
#                "ratings":{
#                   "percentage":0,
#                   "votes":0,
#                   "loved":0,
#                   "hated":0
#                }
#             }
#          },
#          {
#             "show":{
#                "title":"Hello Ladies",
#                "year":2013,
#                "url":"http:\/\/trakt.tv\/show\/hello-ladies",
#                "first_aired":1380519000,
#                "first_aired_iso":"2013-09-29T22:30:00-04:00",
#                "first_aired_localized":1380519000,
#                "first_aired_utc":1380508200,
#                "country":"United States",
#                "overview":"Hello Ladies is loosely based on a 2011 stand-up routine and follows Merchant as an awkward, overly confident Englishman trying to date in Los Angeles \u2013 where his attempts to infiltrate the world of beautiful people are not successful.",
#                "runtime":30,
#                "network":"HBO",
#                "air_day":"Sunday",
#                "air_day_localized":"Sunday",
#                "air_day_utc":"Sunday",
#                "air_time":"10:30pm",
#                "air_time_localized":"10:30pm",
#                "air_time_utc":"7:30pm",
#                "certification":"TV-MA",
#                "imdb_id":"tt2378794",
#                "tvdb_id":"265609",
#                "tvrage_id":"32368",
#                "images":{
#                   "poster":"http:\/\/slurm.trakt.us\/images\/posters\/21479.13.jpg",
#                   "fanart":"http:\/\/slurm.trakt.us\/images\/fanart\/21479.13.jpg",
#                   "banner":"http:\/\/slurm.trakt.us\/images\/banners\/21479.13.jpg"
#                },
#                "ratings":{
#                   "percentage":63,
#                   "votes":80,
#                   "loved":55,
#                   "hated":25
#                },
#                "genres":[
#                   "Comedy"
#                ]
#             },
#             "episode":{
#                "season":1,
#                "number":7,
#                "title":"The Wedding",
#                "overview":" Stuart tries to change the seating plan at a wedding; Jessica waits to hear about her call-back audition for a network show.",
#                "url":"http:\/\/trakt.tv\/show\/hello-ladies\/season\/1\/episode\/7",
#                "first_aired":1384151400,
#                "first_aired_iso":"2013-11-10T22:30:00-05:00",
#                "first_aired_localized":1384151400,
#                "first_aired_utc":1384140600,
#                "images":{
#                   "screen":"http:\/\/slurm.trakt.us\/images\/fanart\/21479-940.13.jpg"
#                },
#                "ratings":{
#                   "percentage":80,
#                   "votes":1,
#                   "loved":1,
#                   "hated":0
#                }
#             }
#          }
#       ]
#     }
#   ]
